# Generated by Django 5.2.4 on 2025-08-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('activity', models.CharField(choices=[('WA', 'Walk'), ('SL', 'Sleep'), ('EA', 'Eat'), ('SM', 'Smalltalk')], max_length=2)),
                ('place', models.CharField(choices=[('O', 'Office'), ('P', 'Park'), ('F', 'Forest'), ('C', 'Cafe')], max_length=1)),
            ],
        ),
    ]
