# Generated by Django 5.2.4 on 2025-08-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaktime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='activity',
        ),
        migrations.AddField(
            model_name='break',
            name='Walk Sleep Eat Smalltalk',
            field=models.CharField(default='Smalltalk', verbose_name='Activity'),
        ),
    ]
