# Generated by Django 5.2.4 on 2025-08-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaktime', '0002_remove_break_activity_break_walk_sleep_eat_smalltalk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='Walk Sleep Eat Smalltalk',
        ),
        migrations.AddField(
            model_name='break',
            name='activity',
            field=models.CharField(choices=[('WA', 'Walk'), ('SL', 'Sleep'), ('EA', 'Eat'), ('SM', 'Smalltalk')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='break',
            name='place',
            field=models.CharField(choices=[('O', 'Office'), ('P', 'Park'), ('F', 'Forest'), ('C', 'Cafe')], default=1, max_length=1),
        ),
    ]
