# Generated by Django 5.2.4 on 2025-08-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaktime', '0003_remove_break_walk_sleep_eat_smalltalk_break_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='recreation',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
    ]
