# Generated by Django 5.2.4 on 2025-08-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaktime', '0004_break_recreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='activity',
            field=models.CharField(choices=[('WA', 'Walk'), ('SL', 'Sleep'), ('EA', 'Eat'), ('SM', 'Smalltalk')], default='WA', max_length=2),
        ),
        migrations.AlterField(
            model_name='break',
            name='place',
            field=models.CharField(choices=[('O', 'Office'), ('P', 'Park'), ('F', 'Forest'), ('C', 'Cafe')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='break',
            name='recreation',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5),
        ),
    ]
