# Generated by Django 5.2.4 on 2025-08-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('sleeping_place', models.CharField(choices=[('B', 'Bed'), ('S', 'Sofa'), ('F', 'Floor')], max_length=1)),
            ],
        ),
    ]
