# Generated by Django 5.2.4 on 2025-08-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleeptime', '0002_sleepinterval_recreation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepinterval',
            name='sleeping_place',
            field=models.CharField(choices=[('B', 'Bed'), ('S', 'Sofa'), ('F', 'Floor')], default='B', max_length=1),
        ),
    ]
