# Generated by Django 5.2.4 on 2025-08-02 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(choices=[('W', 'Water'), ('C', 'Coffee'), ('B', 'Beer')], max_length=1)),
                ('milliliters', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
    ]
